### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by gtb104** [srowhani/ember-artisans#1]
We're trying this addon out, and ran across an issue. Testing. I'd like to unit test the functions in the worker file, but since it's in the `root/workers` directory and not in `root/addon` directory, it doesn't seem to be available for import. Any ideas?

**Comment by gtb104** [comment]
So I was able to get Ember to see the worker file by moving it to `/addon/workers` directory, then soft linking that back to `/workers`.

The problem now is that the worker is using CommonJS module syntax, but our Ember code is written in ES6 module syntax. Is there a reason the worker needs to be in CommonJS? Or some other workaround I could try?

**Comment by srowhani** [comment]
Hey, thanks for raising an issue, and investigating. The main reason for choosing the cjs syntax, over es6, was mainly due to that certain keywords in the ember paradigm like `export` are not recognized by the browser. I could sort of foresee people running into issues with it, and it garbling an exception.

Another thought I had early on was to have it be transpiled, the same way the rest of the tree's are being - but I couldn't just do it the same way as the rest of the app, because workers have their own import syntax.

I can describe further what should be done to get es6, but at the time, the cost of doing this didn't really reward much as cjs is sort of already common in the ember world - so just went with that.

**Comment by gtb104** [comment]
So I figured it out.

My failure was that I was trying to `import` the exported functions from the worker. Then I realized that the worker is probably in the `/assets` directory just like it is for a normal build. I was able to create the worker in the `before` hook of the integration test, and call it just like any other async function during each test.

**Comment by srowhani** [comment]
Glad that you got it working, thanks for the update!
